- aca_plugin_toolbox/connections.py
> Add fixes for updated connection filtering

- .gitignore
- Dockerfile
- docker-compose.yml
- docker-compose_alice_bob.yml
- ngrok-wait.sh
- startup.sh
Needs to be tested!
Signed-off-by: Adam Burdett <burdettadam@gmail.com>
> Alice n Bob docker agents

- aca_plugin_toolbox/issuer.py
> Fix schema/message mismatch in send-credential

- aca_plugin_toolbox/credential_definitions.py
@ken-ebert I'm not sure if this is a recent change or not. This change was required for me to be able to run the plugin, though.
> Fix reference to util in credential_definitions

- .gitignore
Signed-off-by: Sam Curren <telegramsam@gmail.com>
> updated ignore.

- Dockerfile
Signed-off-by: Sam Curren <telegramsam@gmail.com>
> Updated dockerfile to use local code for plugin

- aca_plugin_toolbox/issuer.py
> Fix credential send

- aca_plugin_toolbox/issuer.py
Don't merge until you test it lol
> Don't try to deserialize credential_preview again

- README.md
> Fix `pip install` URL to point to HL

- acapy_plugin_toolbox/holder.py
- acapy_plugin_toolbox/issuer.py
- acapy_plugin_toolbox/static_connections.py
> Fix queries with recent tag elimination

- Dockerfile
- acapy_plugin_toolbox/connections.py
fetch_activity is no longer a method on connection_record
> Minor fixes

- Dockerfile
- acapy_plugin_toolbox/http_ws.py
- acapy_plugin_toolbox/schemas.py
- acapy_plugin_toolbox/static_connections.py
- docker-compose.yml
- docker-compose_alice_bob.yml
- startup.sh
Not quite locked in to ACA-Py 0.4.0 release due to a few needed updates but this is significantly closer.
> ACA-Py 0.4.0 related fixes

- acapy_plugin_toolbox/util.py
> Fix timezone in timestamps

- acapy_plugin_toolbox/holder.py
- acapy_plugin_toolbox/issuer.py
Fix an error caused by changes in ACA-Py version 0.4.1
> Fix CredentialProposalRequestSchema name change

- README.md
- acapy_plugin_toolbox/__init__.py
- acapy_plugin_toolbox/basicmessage.py
- acapy_plugin_toolbox/connections.py
- acapy_plugin_toolbox/credential_definitions.py
- acapy_plugin_toolbox/dids.py
- acapy_plugin_toolbox/group/all.py
- acapy_plugin_toolbox/group/connections.py
- acapy_plugin_toolbox/group/holder.py
- acapy_plugin_toolbox/group/issuance.py
- acapy_plugin_toolbox/holder.py
- acapy_plugin_toolbox/issuer.py
- acapy_plugin_toolbox/schemas.py
- acapy_plugin_toolbox/static_connections.py
- setup.py
- startup.sh
And add groups to load multiple based on category.
> Make each admin protocol individually loadable

- README.md
> Add docker demo instructions to the README

- acapy_plugin_toolbox/group/all.py
- acapy_plugin_toolbox/taa.py
> Add TAA acceptance

- Dockerfile
This will help alleviate docker cache invalidation issues and also
provide discrete changes when we expect changes in the ACA-Py we are
pulling in.
> Point to specific commit in Dockerfile

- Dockerfile
> Point to newer commit with pre_verify fix

- Dockerfile
> Include invite print flush fix

- Dockerfile
> More invitation print buffer fixes

- acapy_plugin_toolbox/payments.py
> Add @admin_only to payment handlers

- requirements.txt
> fix: acapy version in requirements

- acapy_plugin_toolbox/basicmessage.py
- acapy_plugin_toolbox/connections.py
- acapy_plugin_toolbox/credential_definitions.py
- acapy_plugin_toolbox/holder.py
- acapy_plugin_toolbox/issuer.py
- acapy_plugin_toolbox/schemas.py
- acapy_plugin_toolbox/static_connections.py
- requirements.txt
This PR gets Credentials and Presentations working again after upstream changes preparatory to the pending 0.6.0 release.
> fix: creds and pres after 0.6.0 breaking changes

- acapy_plugin_toolbox/holder.py
- acapy_plugin_toolbox/issuer.py
- demo/Dockerfile.demo
- demo/configs/default.yml
> fix: upstream breaking changes to credentials and presentations

- demo/ngrok-wait.sh
> fix: ws value not passed to container in demo

- acapy_plugin_toolbox/holder.py
> fix: credential labels

- .commitlint.config.js
- .pre-commit-config.yaml
- acapy_plugin_toolbox/issuer.py
- acapy_plugin_toolbox/mediator.py
- acapy_plugin_toolbox/routing.py
- demo/Dockerfile.demo
- docker/Dockerfile
- docker/README.md
- docker/default.yml
- requirements.dev.txt
- requirements.txt
- setup.cfg
Updates and fixes for using the toolbox plugin against ACA-Py 0.6.0
> Compatibility fixes for ACA-Py 0.6.0

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- SECURITY.md
> chore: add documents required by repolint

- acapy_plugin_toolbox/taa.py
> fix: ledger not ready on get taa accept request

- acapy_plugin_toolbox/issuer.py
Fixed:
- IndyProofRequest object has no attribute get error
- Issuer credential list message incorrect type
- Issuer presentation list message incorrect type
> Fix presentation and issuance errors

- acapy_plugin_toolbox/basicmessage.py
- demo/Dockerfile.demo
- docker/default.yml
And a couple docker optimizations.
> fix: basic messages not sending to recipients

- int/tests/__init__.py
- int/tests/test_basicmessage.py
- int/tests/test_connections.py
> refactor: simplify logging

- acapy_plugin_toolbox/connections.py
Signed-off-by: Char <char@indicio.tech>
> fix: add assign_thread_from function to ReceiveInvitationHandler

- acapy_plugin_toolbox/holder/v0_1/messages/pres_request_received.py
- tests/holder/test_events.py
> fix: presentation as holder failure on cred retrieval

- acapy_plugin_toolbox/connections.py
- acapy_plugin_toolbox/issuer.py
- int/tests/test_credentialdefinitions.py
- tests/test_getlisthandler.py
Added unit test for connections.py GetListHandler class
> feat:added_connections_GetListHandler_test

- demo/docker-compose.alice-bob-local.yml
Signed-off-by: Char Howland <char@indicio.tech>
> feat: add docker-compose for agent local connections

- poetry.lock
- pyproject.toml
> feat: update to 0.7.3 of ACA-Py

- acapy_plugin_toolbox/holder/v0_1/messages/cred_get_list.py
- int/tests/test_holder.py
> fix: holder cred-get-list returns only holder creds

- demo/README.md
Signed-off-by: Micah Peltier <micah6_8@yahoo.com>
> docs: handling interlaced QR code

- demo/configs/mediator.yml
Signed-off-by: Micah Peltier <micah6_8@yahoo.com>
> feat: update mediator wallet to bypass encoding problems for demo

- int/poetry.lock
- int/pyproject.toml
- int/tests/test_holder.py
- int/tests/test_presentation.py
> test: update acapy-client in int tests

- .github/workflows/code-quality-check.yml
- .github/workflows/tests.yml
- acapy_plugin_toolbox/credential_definitions.py
- acapy_plugin_toolbox/schemas.py
Signed-off-by: Peter Strobel <peter@indicio.tech>
> feat: toolbox can retreive ACA-Py records 
